// Shared lint config for the non-Nuxt workspace packages (core, e2e, tools).
// apps/web uses the config generated by @nuxt/eslint.
import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import prettier from 'eslint-config-prettier'

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/coverage/**',
      'apps/**',
      'reference/**',
      '**/playwright-report/**',
      '**/test-results/**',
      'packages/core/test/fixtures/**',
      // page snippets injected into the prototype closure (not modules)
      'tools/poc-harness/src/*.js',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strict,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
  prettier,
)
